name: Release

on:
  create:
    branches: [ master ]
    tags: ["release-*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        persist-credentials: false

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Attempt release
      shell: bash
      run: |
        git config user.name "jaegertracingbot"
        git config user.email "jaegertracingbot+jaeger-tracing@googlegroups.com"
        git config credential.helper "store --file=.git/credentials"
        echo "https://${{ secrets.JAEGERTRACINGBOT_GITHUB_TOKEN }}" > .git/credentials
        echo check github credentials
        curl -H "Authorization: token ${{ secrets.JAEGERTRACINGBOT_GITHUB_TOKEN }}" https://api.github.com/users/jaegertracingbot -I
        export TRAVIS_TAG=${GITHUB_REF##*/}
        ./travis/release.sh
